-- =========================================================================
-- ARCHITECTURE EVENT-DRIVEN : Flux Horaire et Conjoncture
-- =========================================================================

-- 1. Table tampon pour les annonces streamées (ultra-rapide, peu d'historique)
CREATE TABLE IF NOT EXISTS public.raw_listings_stream (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_title TEXT NOT NULL,
    raw_price TEXT NOT NULL,
    price_parsed BIGINT,
    source TEXT NOT NULL,
    model_id TEXT, -- Mappé après parsing
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT raw_listings_stream_unq UNIQUE (raw_title, raw_price)
);

-- Index pour accélérer le requêtage récent
CREATE INDEX IF NOT EXISTS idx_raw_stream_fetched_at ON public.raw_listings_stream(fetched_at DESC);
CREATE INDEX IF NOT EXISTS idx_raw_stream_model ON public.raw_listings_stream(model_id);

-- 2. Table pour les signaux d'actualités macro-économiques
CREATE TABLE IF NOT EXISTS public.market_news_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_coef NUMERIC(4,3) NOT NULL DEFAULT 1.000, -- ex: 1.050 (+5%)
    headline TEXT,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_news_signals_date ON public.market_news_signals(captured_at DESC);

-- 3. Table de cache des prix horaires
CREATE TABLE IF NOT EXISTS public.model_prices_hourly (
    model_id TEXT PRIMARY KEY,
    computed_median BIGINT NOT NULL,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Procédure stockée de rafraîchissement horaire
-- Combine le stream récent (48h) et le dernier signal macro-économique
CREATE OR REPLACE FUNCTION public.refresh_hourly_market_trends()
RETURNS void AS $$
DECLARE
    latest_coef NUMERIC(4,3);
BEGIN
    -- Récupérer le dernier coefficient (ex: 1.05 pour un gel d'importation)
    SELECT current_coef INTO latest_coef 
    FROM public.market_news_signals 
    ORDER BY captured_at DESC 
    LIMIT 1;

    IF latest_coef IS NULL THEN
        latest_coef := 1.000;
    END IF;

    -- Vider l'ancien cache ou faire un UPSERT
    -- On va faire un UPSERT pour garder la table propre
    INSERT INTO public.model_prices_hourly (model_id, computed_median, last_updated)
    SELECT 
        r.model_id,
        (PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY r.price_parsed) * latest_coef)::BIGINT as computed_median,
        NOW() as last_updated
    FROM public.raw_listings_stream r
    WHERE r.model_id IS NOT NULL 
      AND r.price_parsed IS NOT NULL 
      AND r.price_parsed > 100000 -- Filtrer les faux prix (1 DA)
      AND r.fetched_at >= NOW() - INTERVAL '48 hours'
    GROUP BY r.model_id
    ON CONFLICT (model_id) 
    DO UPDATE SET 
        computed_median = EXCLUDED.computed_median,
        last_updated = EXCLUDED.last_updated;
        
    -- Optionnel : Nettoyer les annonces stream de plus de 7 jours pour ne pas gonfler la table
    DELETE FROM public.raw_listings_stream WHERE fetched_at < NOW() - INTERVAL '7 days';
END;
$$ LANGUAGE plpgsql;
